### ISSUE TITLE
docker 独立部署选用SQLite数据库时报错

### ISSUE THREAD

**Issue by YinAoXiong** [lizheming/waline#10]
具体的docker 运行代码如下所示：
```
docker run -it --name waline -v /home/ubuntu/docker/waline/waline.sqlite:/waline.sqlite -e SQLITE_PATH=/ lizheming/waline
```
报错内容如下所示：
```
[2020-11-20T05:01:28.882] [1] [INFO] - Server running at http://127.0.0.1:8360
[2020-11-20T05:01:28.905] [1] [INFO] - ThinkJS version: 3.2.12
[2020-11-20T05:01:28.906] [1] [INFO] - Environment: production
[2020-11-20T05:01:28.906] [1] [INFO] - Workers: 1
TypeError: appId must be a string
    at Object.init (/opt/waline/node_modules/leancloud-storage/dist/node/init.js:94:21)
    at Object.<anonymous> (/opt/waline/src/service/storage/leancloud.js:5:4)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at exports.interopRequire (/opt/waline/node_modules/think-loader/loader/util.js:14:13)
    at /opt/waline/node_modules/think-loader/loader/common.js:16:26
```

**Comment by lizheming** [comment]
LeanCloud 的配置写在了最外面导致会一直执行了，之前测试的时候我的环境变量是叠加的，就没有注意到这件事。已经修复了，稍等 Docker 自动构建完成之后你用新的镜像应该就可以了。（或者你现在随便写个 appId 和 appKey 应该也行？）

**Comment by YinAoXiong** [comment]
> LeanCloud 的配置写在了最外面导致会一直执行了，之前测试的时候我的环境变量是叠加的，就没有注意到这件事。已经修复了，稍等 Docker 自动构建完成之后你用新的镜像应该就可以了。（或者你现在随便写个 appId 和 appKey 应该也行？）

好的，感谢你优秀的代码，你回复的好快啊:joy:

**Comment by lizheming** [comment]
啊，本地编译了下由发现了另外一个 bug，原来有个地方没注意写死了 leancloud（可耻的匿了... 你再等等构建哈…
ps. 有邮件通知，回复就还挺快的，XDDD

**Comment by YinAoXiong** [comment]
> 啊，本地编译了下由发现了另外一个 bug，原来有个地方没注意写死了 leancloud（可耻的匿了... 你再等等构建哈…
> ps. 谢谢夸奖，欢迎一块来开发呀~ Github 的话有邮件通知，回复就还挺快的，XDDD

ok

**Comment by lizheming** [comment]
@YinAoXiong 我看自动构建成功了，你 pull 下新镜像试试？ps. 我们有 tg 的群，欢迎加到 tg 群里一块交流~

**Comment by YinAoXiong** [comment]
> @YinAoXiong 我看自动构建成功了，你 pull 下新镜像试试？ps. 我们有 tg 的群，欢迎加到 tg 群里一块交流~

好的，我去试试看，已经加群了
