### ISSUE TITLE
Hexo NexT Plugin 运行出错

### ISSUE THREAD

**Issue by rqh656418510** [lizheming/waline#196]
Hexo 安装 `@waline/hexo-next` 插件后，执行 `hexo g` 抛出以下异常信息

```
ERROR Render HTML failed: index.html
TypeError: Cannot read property 'parent' of null
    at Function.exports.update (/usr/local/hexo/node_modules/cheerio/lib/parse.js:55:26)
    at module.exports (/usr/local/hexo/node_modules/cheerio/lib/parse.js:17:11)
    at Function.exports.load (/usr/local/hexo/node_modules/cheerio/lib/static.js:22:14)
    at Hexo.hexoMetaGeneratorInject (/usr/local/hexo/node_modules/hexo/lib/plugins/filter/meta_generator.js:8:21)
    at Hexo.tryCatcher (/usr/local/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/usr/local/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at Promise.each.filter (/usr/local/hexo/node_modules/hexo/lib/extend/filter.js:60:50)
    at tryCatcher (/usr/local/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/usr/local/hexo/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/usr/local/hexo/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/usr/local/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/hexo/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/hexo/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/usr/local/hexo/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/usr/local/hexo/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/usr/local/hexo/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/hexo/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/hexo/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

NexT 的配置如下：

``` yml
waline:
  enable: true
  serverURL: https://example.com
  placeholder: Just go go
  avatar: mm
  meta: [nick, mail, link]
  pageSize: 10
  lang: zh-cn
  visitor: false
  comment_count: true
  requiredFields: []
  libUrl:
```

软件版本如下：

- next: 7.8
- hexo: 3.9.0
- node: 10.14.2
- hexo-cli: 2.0.0
- linux: CentOS7.9

**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [ ] Vercel
    - [ ] CloudBase
    - [x] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [ ] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [ ] CloudBase
    - [ ] MongoDB
    - [x] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL
    - [ ] Github

**Comment by njzjz** [comment]
@rqh656418510 明显是版本太低了

**Comment by rqh656418510** [comment]
@njzjz 谢谢 ，我试试升级下版本
