### ISSUE TITLE
可以考虑提供部署在自己服务器的模板

### ISSUE THREAD

**Issue by eallion** [lizheming/Waline#2]
可以考虑提供部署在自己服务器的模板，有的人应该有闲置服务器。

**Comment by lizheming** [comment]
嗯，可以用下面的脚本启动。或者之后构建一个镜像来处理不错。

```js
const http = require('http');
const Waline  = require('@waline/vercel');
http.createServer( Waline({}) ).listen(3000);
```

**Comment by lizheming** [comment]
已增加 [lizheming/waline](https://hub.docker.com/r/lizheming/waline) 镜像，使用方式

```shell
docker run -p 8360:8360 lizheming/waline
```

**Comment by eallion** [comment]
> 已增加 [lizheming/waline](https://hub.docker.com/r/lizheming/waline) 镜像，使用方式
> 
> ```shell
> docker run -p 8360:8360 lizheming/waline
> ```
```
internal/modules/cjs/loader.js:883

throw err;

^


Error: Cannot find module '/opt/waline/${WORKDIR}/vanilla.js'

at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)

at Function.Module._load (internal/modules/cjs/loader.js:725:27)

at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)

at internal/main/run_main_module.js:17:47 {

code: 'MODULE_NOT_FOUND',

requireStack: []

}
```

**Comment by lizheming** [comment]
@eallion 已经修复

```bash
docker run -e LEAN_ID=YOUR_LEAN_ID -e LEAN_KEY=YOUR_LEAN_KEY -p 8360:8360 lizheming/waline
```

**Comment by eallion** [comment]
LeanCloud 国际版可以，国内版不行。

**Comment by lizheming** [comment]
@eallion 等待 #5 解决。其实就是增加一个环境配置，并增加相关文档说明，你要有时间的话可以提个 PR 帮忙处理下。
